### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Pokerpoke** [Pokerpoke/LeetCode#2]
TODO List
- [x] List, Tree destroy
- [x] List, Tree compare
- [x] List, Tree print
- [x] Tutorial in doc
- [x] CI
